version: '3.4'

services:
 
  accountdb:
    container_name: accountdb
    restart: always
    environment:
      SA_PASSWORD: "Pass@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  account.api:
    container_name: account.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__AccountConnectionString=Server=accountdb;Database=AccountDb;User Id=sa;Password=Pass@123;"
    depends_on:
      - accountdb
    ports:
      - "8001:80"

  account.consoleapp:
    container_name: account.consoleapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__AccountConnectionString=Server=accountdb;Database=AccountDb;User Id=sa;Password=Pass@123;"
    depends_on:
      - accountdb
    ports:
      - "8002:80"
