version: '3.4'

services:
  account.api:
    image: ${DOCKER_REGISTRY-}accountapi
    build:
      context: .
      dockerfile: Services/Account/Account.Api/Dockerfile

  accountdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  account.consoleapp:
    image: ${DOCKER_REGISTRY-}accountconsoleapp
    build:
      context: .
      dockerfile: Services/Account/Account.Console/Dockerfile

